name: "citeas-on-requirements"
description: "Apply citeAs to the elements of a requirements.txt file to make an ACKNOWLEDGMENTS file"
author: "Daniel N Bullock"
inputs:
  inputFile:
    description: "Input file to parse & make citations for"
    default: "/app/test/testFiles/requirements_default.txt"
outputs:
  myOutput:
    description: "ACKNOWLEDGMENTS.md file, a lightly formatted software bibliography"
runs:
  using: "docker"
  image: "Dockerfile"