name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: DanNBullock/citeas-on-requirements@master

      - name: Check outputs
        run: |
          test -f "ACKNOWLEDGMENTS.md"
